### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by B-Interactive** [wojtkowiak/electron-windows-osk#2]
Using the line of code pulled from the provided sample, it's throwing a SyntaxError, pointing to the identifier, `WindowsOSK`.

My index.js:
`import WindowsOSK from 'electron-windows-osk';`
`const { app, BrowserWindow } = require('electron');`

The output:

App threw an error during load

> D:\Electron\project\index.js:1
> (function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import **WindowsOSK** from 'electron-windows-osk';
> 
> SyntaxError: Unexpected identifier
>     at new Script (vm.js:74:7)
>     at createScript (vm.js:246:10)
>     at Object.runInThisContext (vm.js:298:10)
>     at Module._compile (internal/modules/cjs/loader.js:678:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
>     at loadApplicationPackage (D:\Electron\project\node_modules\electron\dist\resources\default_app.asar\main.js:287:12)
>     at Object.<anonymous>

**Comment by glebmachine** [comment]
imports not transpiled in your case, use require as well

**Comment by zainlateef** [comment]
When I use require, I get an "Invalid access to memory location" error, something having to do with addon.node. Any ideas?
